### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [2]:
import numpy as np
vector = np.random.rand(1, 10)
print(vector, vector.shape)

[[0.79490578 0.70975027 0.35851317 0.29641047 0.49427219 0.22841571
  0.95480634 0.60884963 0.22378146 0.61882239]] (1, 10)


In [3]:
matrix = np.array([[11, 14, 17], [20, 23, 26], [29, 32, 35]])
print(matrix, matrix.shape)

[[11 14 17]
 [20 23 26]
 [29 32 35]] (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [4]:
vector = [(x + 10).round(2) for x in vector]
print(vector)

[array([10.79, 10.71, 10.36, 10.3 , 10.49, 10.23, 10.95, 10.61, 10.22,
       10.62])]


In [22]:
matrix = matrix*2
print(matrix)

[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [5]:
vector = [x**2 for x in vector]
print(vector)

[array([116.4241, 114.7041, 107.3296, 106.09  , 110.0401, 104.6529,
       119.9025, 112.5721, 104.4484, 112.7844])]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [6]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [7]:
result_matrix = np.dot(B, A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [60]:
C

array([[0],
       [1]])

### розмірність матриці (у ширину, кількість колонок: 3) співпадає з розмірністю вектора (висота: 3) = можна помножити

In [8]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

### розмірність матриці (у ширину, кількість колонок: 2) співпадає з розмірністю вектора (висота: 2) = можна помножити

In [9]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [10]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [74]:
type(vector)

list

In [11]:
vector = vector[0]

In [12]:
print(vector.shape)

(10,)


In [16]:
vector

array([116.4241, 114.7041, 107.3296, 106.09  , 110.0401, 104.6529,
       119.9025, 112.5721, 104.4484, 112.7844])

In [17]:
vector.T

array([116.4241, 114.7041, 107.3296, 106.09  , 110.0401, 104.6529,
       119.9025, 112.5721, 104.4484, 112.7844])

In [19]:
vector.T.shape

(10,)

### після транспонування вектор залишився без змін

In [14]:
column_vector = np.expand_dims(vector, axis=1)

print(column_vector)
print(column_vector.shape)

[[116.4241]
 [114.7041]
 [107.3296]
 [106.09  ]
 [110.0401]
 [104.6529]
 [119.9025]
 [112.5721]
 [104.4484]
 [112.7844]]
(10, 1)


In [18]:
trans_column_vector = column_vector.T

print(trans_column_vector)
print(trans_column_vector.shape)

[[116.4241 114.7041 107.3296 106.09   110.0401 104.6529 119.9025 112.5721
  104.4484 112.7844]]
(1, 10)


### vector, trans_column_vector схожі, але є різними об'єктами з різними розмірностями